import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import { NestExpressApplication } from '@nestjs/platform-express';
import { AppModule } from './app.module';
import 'source-map-support/register';
import { BadRequestException, ValidationPipe } from '@nestjs/common';
import { ExceptionsFilter } from './exception.filter';
import { LoggingInterceptor } from './logging.interceptor';
import { Oid4vcAgentProvider } from './oid4vc/agent/oid4vc-agent.provider';
import { Oid4vcConfig } from './oid4vc/oid4vc.config';

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule, {
    logger: ['log', 'error', 'warn', 'debug', 'verbose'],
  });

  // Mount the Credo OID4VCI/OID4VP Express routers *before* `setGlobalPrefix`
  // so wallets reach the protocol endpoints at the absolute URLs declared in
  // the issuer/verifier metadata (i.e. without the `/v1` Nest prefix).
  const oid4vcAgent = app.get(Oid4vcAgentProvider);
  const oid4vcConfig = app.get(Oid4vcConfig);
  // Credo's openid4vc routers register a post-handler middleware that calls
  // `next()` after the response has been sent (for `agentContext.endSession()`
  // cleanup). If we mount the router directly, that `next()` propagates back
  // into Express's parent stack and re-enters Nest's middleware (CORS delegate,
  // 404 fallback, exception filter) which all try to setHeader on a finalized
  // response and crash with "Cannot set headers after they are sent". Wrapping
  // the router so it swallows `next()` once headers are sent keeps the cleanup
  // intact while terminating the request at the credo boundary.
  const terminating = (router: typeof oid4vcAgent.issuerRouter) => {
    return (req: any, res: any, next: any) => {
      router(req, res, (err: unknown) => {
        if (err) return next(err);
        if (res.headersSent || res.writableEnded) return;
        next();
      });
    };
  };
  app.use(oid4vcConfig.issuerPath, terminating(oid4vcAgent.issuerRouter));
  app.use(oid4vcConfig.verifierPath, terminating(oid4vcAgent.verifierRouter));

  app.useGlobalFilters(new ExceptionsFilter());
  app.useGlobalInterceptors(new LoggingInterceptor());
  // All Nest routes (DID lookups, OID4VC issuer/verifier app surface,
  // did:key-authenticated payment routes) live under the global `/v1`
  // prefix. The Credo OID4VCI/OID4VP routers were already mounted above
  // at their absolute protocol paths, before `setGlobalPrefix`, so they
  // are unaffected.
  app.setGlobalPrefix('v1');
  app.useGlobalPipes(
    new ValidationPipe({
      exceptionFactory: (errors) => {
        const result = errors.map((error) => ({
          property: error.property,
          message: error.constraints[Object.keys(error.constraints)[0]],
        }));
        return new BadRequestException(result);
      },
      transform: true,
      stopAtFirstError: true,
    }),
  );

  const options = new DocumentBuilder()
    .setTitle('Pawn API')
    .setVersion('0.0.1')

    .setVersion('v1')
    .addBearerAuth({
      description: '(JWT) generated by the /v1/auth/sign-in endpoint',
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT',
    })
    // Credential-gated routes (e.g. `POST /v1/did/create/transactions`)
    // accept a wallet-presented SD-JWT VC via the
    // `X-Credential-Presentation` header. Register it as an apiKey
    // scheme so Swagger UI prompts for it under "Authorize".
    .addApiKey(
      {
        type: 'apiKey',
        name: 'x-credential-presentation',
        in: 'header',
        description:
          'Compact SD-JWT VC presentation that proves possession of a ' +
          "device-attestation credential bound to the caller's did:key. " +
          'Obtained by completing the OID4VCI pre-authorized-code flow ' +
          'advertised by `POST /v1/link/response` and presenting ' +
          "the issued credential with the holder's `cnf.kid` binding. " +
          'Required on credential-gated endpoints such as ' +
          '`POST /v1/did/create/transactions`.',
      },
      'x-credential-presentation',
    )
    .build();
  const document = SwaggerModule.createDocument(app, options, {});
  SwaggerModule.setup('docs', app, document);

  await app.listen(3000);
}
bootstrap();
